autorouting/main

Yikuan's thing.md

i made an md

---

cyberbullying.md

i made a cring

---

onevehicleroutegen.py
route.txt

so that we can actually gen the maps link

Updated it to write to text file

---

locations.txt
onevehicleroutegen.py
route.txt

made the program read from file. UI = cool

updated UI

---

genmapslink.py
onevehicleroutegen.py

fixed bugz

---

genmapslink.py
route.txt
routegen.py

changed some stuff. it's still broken tho. someone help :cry:

---

onevehicleroutegen.py

changed -1 to 0.07 'cause James Bond

---

onevehicleroutegen.py

tho still isn't completely accurate 'cause we intentionally set distance A -> B to the wrong distance.

Changed output unit type

---

onevehicleroutegen.py

that way it will always pick A -> B unless the distance A -> B is greater than the distance from alaska to florida lol

just changed the everything except for a -> B number to be bigger

---

onevehicleroutegen.py

added faulty input check

---

genmapslink.py
launchprogram.command

made it work

---

README.md

updated the docs

---

onevehicleroutegen.py

function is a type of variable

made it so that the only global variables are functions

---

genmapslink.py

made it open link in browser

---

multi_vehicle_routegen.py

found a typo, and fixed it.

---

gui.py
locations.txt

tried to add simple gui

---

gui.py
locations.txt

fixed an issue

---

gui.py
onevehicleroutegen.py
route.txt

fixed a bug

---

gui.py

made gui open genmapslink.py

---

savegraph.py

save graph lol

---

onevehicleroutegen.py

'cause that's what we measured with osmnx

made sure output in meters

---

run_gui_multi.command

created excecutable for macos

---

gui.py
onevehicleroutegen.py

reverted to better version

---

run_gui_multi.sh

'cause we might have linux users amirite

created linux excecutable

---

run_gui_single.bat
run_gui_single.command
run_gui_single.sh

created shell scripts and batchfiles for single vehicle gui

---

onevehicleroutegen.py

added comments ig

---

gui_multi.py

removed city input from guimulti

---

gui.py

added comments

---

onevehicleroutegen.py
route.txt

removed the cycle from onevehicle

---

onevehicleroutegen.py

fixed in on onevehicle

---

index.html

lol it doesn't communicate with the program yet

made simple gui (single vehicle)

---

webgui.py

made the cgi file

---

index.html

made form non-destructive

---

index.html

changed literally one thing

---

index.html

added drop shadow

---

index.html

made fields required

---

genmapslink.py
genmapslink_web.py

python's built-ins are ngl pretty darn cool

made url creation more secure

---

style.css

rounded all of the corners even more

---

index.html
style.css

made resize and centering better

---

database.py

finished all the code

---

index.html

made flexbox less rigid

---

addressrouter/src/basicrouter.py

There was something I didn't see so I changed it 'cause I thought it was wrong sorry @amwang9276

Revert the code

---

addressrouter/src/basicrouter.py

Make addIntermediateAddresses

---

addressrouter/src/basicrouter.py
addressrouter/src/maputil.py

Create getmappedaddresses and genmapslink

---

addressrouter/src/basicrouter.py
addressrouter/src/multi_vehicle_route_gen.py

distancematrix is self._distancematrix

Clean up redundant parameter in create_data_model

---

addressrouter/src/basicrouter.py

For targeting and deleting addresses. Please test and review.

Make deleteAddresses and getIndex

---

addressrouter/tests/basictester.py
addressrouter/tests/testfiles/test1.txt

I know the code looks whack. Test it and write a review.

Made a test that reads from file

---

addressrouter/src/basicrouter.py

Use tuple instead of string for coord output

---

addressrouter/src/multi_vehicle_route_gen.py

Users should be able to control what gets printed. `print` also interferes with CGI.

Comment out console messages in multivehicle

---

addressrouter/tests/basictester.py

Write test output to file

---

addressrouter/tests/basictester.py

Make % sign signify stop in input parsing in basictester

---

addressrouter/src/basicrouter.py

Fix route_solution in basicrouter; make output parameter for BasicRouter objects

---

addressrouter/src/maputil.py

Cache geocoded data for later usage

---

addressrouter/tests/.gitignore
addressrouter/tests/plotmulti.py
addressrouter/tests/plotmulti_folium.py

Use Folium for plotmulti

---

addressrouter/src/addressrouter/multivehiclerouter.py
addressrouter/tests/plotmulti.py
addressrouter/tests/plotmulti_folium.py
addressrouter/tests/simplemulti.py
addressrouter/tests/testfiles/multiveh_test1.txt

Vehicle capacities, SpanCostCoefficient
